### ISSUE TITLE
PartialEq for keys is enough?

### ISSUE THREAD

**Issue by limira** [axelf4/lis#1]
Hi, I am not good in math, but I think that in:
```rust
pub fn diff_by_key<S, T, K: Eq + Hash>()
```
`K: PartialEq` is enough. Do you think so?

Also, I think `old`/`new`... is better than `a`/`b`... (names of `diff_by_key` arguments).

**Side talk**: I am the one who talked to you in https://github.com/axelf4/dumle/issues/1. The last few months I switch my focus to [Mika](https://gitlab.com/limira-rs/mika). Now I am trying to implement a fallback mode to handle list change for Mika. The first try is to use your *lis* crate, hoping that goes well. If you are still interested in a frontend framework, you may want to have a look at [its page - with integrated demo](https://limira-rs.gitlab.io/mika/).

**Comment by axelf4** [comment]
Well, the immediate complication with relaxing the bound to `K: PartialEq` is that the keys are put in a `HashMap` which requires `K: Eq`. Also, correct me if I'm wrong, but I think that the lack of reflexivity with `PartialEq` would mean that diffing `[NaN]` against `[NaN]` could report a removal followed by an insertion, which, while not *wrong*, is a little strange. Do you have a case where you need only `PartialEq`?

> Also, I think `old`/`new`... is better than `a`/`b`... (names of `diff_by_key` arguments).

I agree. Maybe `n`/`p` for new/previous would be a good compromise.

> The last few months I switch my focus to [Mika](https://gitlab.com/limira-rs/mika). Now I am trying to implement a fallback mode to handle list change for Mika.

Mika looks cool! Please let me now if you stumble upon any further issues with lis.

**Comment by limira** [comment]
> Do you have a case where you need only PartialEq?

I have no real use case, just a thought while reading `lis` source code.

> Please let me now if you stumble upon any further issues with lis

I have a problem, I am not sure if a change in `lis` would help or not. [Here is the starting point for the involved code](https://gitlab.com/limira-rs/mika/blob/list-diffing/src/list.rs#L595-629) (with some explanation in comments). It's very great if you have time to dive in and help to solve the problem.

Don't worry if you don't have enough time. I can remove the reference from `Patch`, just store their indices then use them get the values from the `new` Vec.

Note the code is on branch `list-diffing`. You will need Rust nightly (because of `signals`). And run,
```
cargo build --target wasm32-unknown-unknown
```

**Comment by limira** [comment]
Hi, just ignore this. I think that `lis::diff_by_key` is not suitable for my use case. May be I should go a bit deeper and try to use `lis::LisExt::longest_increasing_subsequence_by`.

**Comment by limira** [comment]
After a second thought, I implement a litle code to adapt `lis::diff_by_key` to work with my use case (after giving up the storing of references in `Patch`). It requires at least 3 `Vec` allocations, but I think it is a good start. It can be improved later.
